networks:
  it-mo:

services:

  backend:
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    networks:
      - it-mo
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: spring
    ports:
      - "5432:5432"
    networks:
      - it-mo

  front:
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    ports:
      - "80:80"
    networks:
      - it-mo